'use strict';
const KEY='algebru-thjalfun-v1';
const app=document.querySelector('#app');
let db=read(),person=null,screen='home',quiz=null,session=null,installPrompt=null;
function read(){try{return JSON.parse(localStorage.getItem(KEY))||{students:{}}}catch{return {students:{}}}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(db));document.querySelector('#storageNote').textContent='Vistað.'}catch{document.querySelector('#storageNote').textContent='Ekki tókst að vista; athugaðu geymslu vafrans.'}}
function generated(i){let s=student(),recent=s.recent??(s.recent={}),list=recent[i]??(recent[i]=[]),q;for(let n=0;n<45;n++){q=units[i].make();if(!list.includes(q.prompt))break}list.push(q.prompt);if(list.length>45)list.shift();return q}
function saveActive(){student().active={i:session.i,mode:session.mode,tasks:session.tasks,index:session.index,correct:session.correct,hints:session.hints,answered:session.answered||0};save()}
function resume(){let a=student().active;if(!a||!units[a.i])return dashboard();session={...a,phase:'practice'};screen='practice';if(session.mode==='mastery'&&session.index>=10)return finishPractice();practicePage()}
function safe(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function rand(a,b){return a+Math.floor(Math.random()*(b-a+1))}
function pick(a){return a[rand(0,a.length-1)]}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function opts(answer,other){let values=[...new Set([answer,...other].map(String))];for(let n=1;values.length<3;n++){let candidate=Number.isFinite(Number(answer))?String(Number(answer)+n+3):`${answer} ${n}`;if(!values.includes(candidate))values.push(candidate)}return shuffle(values.slice(0,3))}
function task(prompt,answer,wrong,why,extra={}){return {prompt,answer:String(answer),options:opts(String(answer),wrong.map(String)),why,...extra}}
const graph=(a,b)=>{let x=v=>180+v*27,y=v=>180-v*27;let pts=[-5,5].map(v=>`${x(v)},${y(a*v+b)}`).join(' ');let grid=Array.from({length:11},(_,i)=>{let v=(i-5)*27+180;return `<path d="M${v} 45v270M45 ${v}h270" stroke="#e5eef4"/>`}).join('');return `<svg class="graph" viewBox="0 0 360 360" role="img" aria-label="Hnitakerfi með línu y = ${a}x ${b<0?'− ':'+ '}${Math.abs(b)}">${grid}<path d="M45 180h270M180 45v270" stroke="#526d82" stroke-width="2"/><polyline points="${pts}" fill="none" stroke="#d76b30" stroke-width="4"/><circle cx="180" cy="${y(b)}" r="5" fill="#123c60"/><text x="320" y="173">x</text><text x="188" y="56">y</text><text x="186" y="196">0</text></svg>`};
const units=[
 {name:'Samlagning og frádráttur',group:'Grunnreikningur',intro:'Leggðu saman þegar þú bætir við. Dragðu frá þegar þú tekur eitthvað í burtu. Með stærri tölum geturðu reiknað tugina fyrst og síðan einingarnar.',example:['7 + 5: Byrjaðu á 7 og teldu fimm áfram: 8, 9, 10, 11, 12.','27 + 15: Leggðu fyrst 10 við og færðu 37. Bættu svo 5 við og færðu 42.'],make(){let a=rand(5,40),b=rand(2,20),minus=Math.random()<.5;return minus?task(`${a+b} − ${b} = ?`,a,[a+b,a-1,a+1],`Þú byrjar með ${a+b} og tekur ${b} frá. Þá eru ${a} eftir.`):task(`${a} + ${b} = ?`,a+b,[a,a+b-1,a+b+1],`Teldu ${b} áfram frá ${a}.`)}},
 {name:'Margföldun og deiling',group:'Grunnreikningur',intro:'Margföldun er jafnstórir hópar. Deiling skiptir tölu í jafnstóra hópa.',example:['4 × 3 merkir fjórir hópar með þremur í hverjum: 3 + 3 + 3 + 3 = 12.','12 ÷ 4: Skiptu 12 í fjóra jafna hópa. Það eru 3 í hverjum.'],make(){let a=rand(2,12),b=rand(2,12),divide=Math.random()<.5;return divide?task(`${a*b} ÷ ${a} = ?`,b,[a,a*b,b+1],`Því ${a} × ${b} = ${a*b}, er ${a*b} ÷ ${a} = ${b}.`):task(`${a} × ${b} = ?`,a*b,[a+b,a*b+a,a*b-b],`${a} hópar með ${b} gefa ${a*b}.`)}},
 {name:'Neikvæðar tölur',group:'Tölur og reglur',intro:'Neikvæð tala er minni en núll. Á talnalínu ferðast þú til hægri þegar þú leggur við og til vinstri þegar þú dregur frá.',example:['−3 + 5: Byrjaðu á −3 og farðu fimm skref til hægri. Þú endar á 2.','2 − 5: Farðu fimm skref til vinstri frá 2. Þú endar á −3.'],make(){let a=rand(-20,20),b=rand(2,18),minus=Math.random()<.5,v=minus?a-b:a+b;return task(`${a<0?'−'+Math.abs(a):a} ${minus?'−':'+'} ${b} = ?`,v,[v+1,v-1,minus?a+b:a-b],`Byrjaðu á ${a} og farðu ${b} skref ${minus?'til vinstri':'til hægri'}. Svarið er ${v}.`)}},
 {name:'Reikniröð',group:'Tölur og reglur',intro:'Reiknaðu fyrst það sem er innan sviga, síðan margföldun og deiling og að lokum samlagningu og frádrátt.',example:['3 + 2 × 4: Reiknaðu 2 × 4 = 8 fyrst. Þá fæst 3 + 8 = 11.','(3 + 2) × 4: Reiknaðu svigann fyrst: 5 × 4 = 20.'],make(){let a=rand(2,20),b=rand(2,10),c=rand(2,10),v=a+b*c;return task(`${a} + ${b} × ${c} = ?`,v,[(a+b)*c,a+b+c,v+1],`Margfaldaðu fyrst: ${b} × ${c} = ${b*c}. Leggðu svo ${a} við: ${v}.`)}},
 {name:'Brot',group:'Tölur og reglur',intro:'Brotið 1/4 merkir einn af fjórum jafnstórum hlutum. Til að finna brot af tölu skaltu fyrst deila tölunni með nefnaranum.',example:['1/4 af 20: Skiptu 20 í fjóra jafna hluta: 20 ÷ 4 = 5.','3/4 af 20: Einn fjórði er 5. Þrír fjórðu eru 3 × 5 = 15.'],make(){let d=pick([2,3,4,5]),n=rand(1,d-1),whole=d*rand(3,20),v=n*whole/d;return task(`${n}/${d} af ${whole} = ?`,v,[whole/d,whole*n,v+1],`Fyrst ${whole} ÷ ${d} = ${whole/d}. Síðan ${n} × ${whole/d} = ${v}.`)}},
 {name:'Hvað merkir x?',group:'Upphaf algebru',intro:'x er staðgengill fyrir tölu. Þú getur sett tölu í stað x og reiknað. Sama x táknar sömu tölu í einu dæmi.',example:['Ef x = 4, þá er x + 3 það sama og 4 + 3 = 7.','Ef x = 4, þá er 2x það sama og 2 × 4 = 8.'],make(){let x=rand(2,20),a=rand(2,8),v=a*x;return task(`Ef x = ${x}, hvað er ${a}x?`,v,[a+x,x,v+a],`Settu ${x} í stað x: ${a} × ${x} = ${v}.`)}},
 {name:'Einfalda algebrutjáningu',group:'Upphaf algebru',intro:'Þú getur lagt saman eins liði. x-liðir fara saman við x-liði, en venjulegar tölur fara saman við venjulegar tölur.',example:['3x + 2x = 5x því þrír x-liðir og tveir x-liðir eru fimm x-liðir.','3x + 2 er ekki 5x. Liðirnir eru ólíkir.'],make(){let a=rand(2,15),b=rand(2,15),c=rand(1,20),v=a+b;return task(`Einfaldaðu: ${a}x + ${b}x + ${c}`,`${v}x + ${c}`,[`${v+c}x`,`${a*b}x + ${c}`,`${v}x`],`Leggðu saman x-liðina: ${a}x + ${b}x = ${v}x. Talan ${c} stendur áfram sér.`)}},
 {name:'Jöfnur í einu skrefi',group:'Jöfnur',intro:'Jafna er eins og jafnvægisvog. Þú verður að gera það sama báðum megin við jafnaðarmerkið til að halda henni í jafnvægi.',example:['x + 4 = 9: Dragðu 4 frá báðum hliðum. Þá fæst x = 9 − 4 = 5.','Athugaðu: 5 + 4 = 9. Svarið passar.'],make(){let x=rand(2,30),a=rand(2,25),v=x+a;return task(`x + ${a} = ${v}. Hvað er x?`,x,[v,x+a,x-1],`Dragðu ${a} frá báðum hliðum: x = ${v} − ${a} = ${x}. Athugun: ${x} + ${a} = ${v}.`)}},
 {name:'Jöfnur í tveimur skrefum',group:'Jöfnur',intro:'Þegar bæði margföldun og samlagning eru í jöfnunni skaltu fyrst losa þig við samlagninguna og síðan margföldunina.',example:['2x + 4 = 10: Dragðu 4 frá báðum hliðum: 2x = 6.','Deildu báðum hliðum með 2: x = 3. Athugun: 2 × 3 + 4 = 10.'],make(){let x=rand(2,20),a=rand(2,10),b=rand(2,25),v=a*x+b;return task(`${a}x + ${b} = ${v}. Hvað er x?`,x,[v-b,a*x,x+1],`Dragðu ${b} frá: ${a}x = ${a*x}. Deildu með ${a}: x = ${x}. Athugun: ${a} × ${x} + ${b} = ${v}.`)}},
 {name:'x beggja megin',group:'Jöfnur',intro:'Ef x er báðum megin geturðu tekið x-lið frá báðum hliðum. Síðan leysirðu jöfnuna eins og áður.',example:['3x + 2 = x + 10: Dragðu x frá báðum hliðum: 2x + 2 = 10.','Dragðu 2 frá: 2x = 8. Deildu með 2: x = 4.'],make(){let x=rand(2,15),right=rand(1,6),left=right+rand(2,6),b=rand(1,15),c=(left-right)*x+b;return task(`${left}x + ${b} = ${right}x + ${c}. Hvað er x?`,x,[c-b,left-right,x+1],`Dragðu ${right}x frá: ${left-right}x + ${b} = ${c}. Dragðu ${b} frá og deildu með ${left-right}: x = ${x}.`)}},
 {name:'Setja inn í formúlu',group:'Formúlur',intro:'Formúla lýsir sambandi talna. Þegar þú þekkir gildin skaltu setja þau í stað bókstafanna og reikna.',example:['P = 2l + 2b er formúla fyrir ummál rétthyrnings.','Ef l = 5 og b = 3, þá er P = 2 × 5 + 2 × 3 = 16.'],make(){let l=rand(3,24),b=rand(2,20),v=2*l+2*b;return task(`P = 2l + 2b. Ef l = ${l} og b = ${b}, hvað er P?`,v,[l+b,2*l+b,v+2],`Settu tölurnar inn: P = 2 × ${l} + 2 × ${b} = ${v}.`)}},
 {name:'Einangra stærð í formúlu',group:'Formúlur',intro:'Til að finna óþekkta stærð í formúlu skaltu gera öfuga aðgerð á báðum hliðum, eins og þegar þú leysir jöfnu.',example:['A = l × b. Til að finna l deilirðu báðum hliðum með b.','Þá fæst l = A ÷ b. Ef A = 24 og b = 4, er l = 6.'],make(){let l=rand(3,24),b=rand(2,15),A=l*b;return task(`A = l × b. Ef A = ${A} og b = ${b}, hvað er l?`,l,[A+b,A-b,l+1],`Deildu báðum hliðum með b: l = A ÷ b = ${A} ÷ ${b} = ${l}.`)}},
 {name:'Hnit í hnitakerfi',group:'Línur',intro:'Punktur er skrifaður (x, y). Fyrri talan sýnir hreyfingu til hægri eða vinstri; seinni talan sýnir hreyfingu upp eða niður.',example:['Punkturinn (3, 2): Farðu 3 til hægri frá núlli og síðan 2 upp.','Í (−2, 1) ferð þú 2 til vinstri og 1 upp.'],make(){let x=rand(-4,4),y=rand(-4,4);if(x===0)x=2;if(y===0)y=1;return task(`Farðu ${Math.abs(x)} ${x<0?'til vinstri':'til hægri'} og ${Math.abs(y)} ${y<0?'niður':'upp'}. Hvaða punktur er það?`,`(${x}, ${y})`,[`(${y}, ${x})`,`(${-x}, ${y})`,`(${x}, ${-y})`],`Fyrst er x-hnitið ${x}, svo y-hnitið ${y}. Punkturinn er (${x}, ${y}).`)}},
 {name:'Hallatala og skurðpunktur',group:'Línur',intro:'Í y = ax + b er a hallatalan: hversu mikið y breytist þegar x hækkar um 1. b er y-gildið þegar x = 0.',example:['Í y = 2x + 3 er hallatalan 2 og skurðpunkturinn við y-ásinn 3.','Þegar x = 0 fæst y = 3. Þegar x = 1 fæst y = 5: y hækkaði um 2.'],make(){let a=pick([-4,-3,-2,-1,1,2,3,4]),b=rand(-5,6);return task(`Í y = ${a}x ${b<0?'− '+Math.abs(b):'+ '+b}, hver er hallatalan?`,a,[b,-a,a+b],`Hallatalan er talan sem stendur við x: ${a}. Skurðpunkturinn við y-ásinn er ${b}.`,{graph:graph(a,b)})}},
 {name:'Reikna y með jöfnu línu',group:'Línur',intro:'Línujafnan y = ax + b segir þér y-gildið fyrir hvaða x-gildi sem er. Settu x inn í jöfnuna og reiknaðu.',example:['y = 2x + 3 og x = 4: Settu 4 í stað x.','y = 2 × 4 + 3 = 11. Punkturinn (4, 11) er á línunni.'],make(){let a=pick([-4,-3,-2,-1,1,2,3,4]),b=rand(1,10),x=rand(-4,5),y=a*x+b;return task(`y = ${a}x + ${b}. Hvað er y þegar x = ${x}?`,y,[a+b,x+b,y+a],`Settu x = ${x} inn: y = ${a} × ${x} + ${b} = ${y}.`,{graph:graph(a,b)})}},
 {name:'Finna jöfnu línu',group:'Línur',intro:'Finndu fyrst hve mikið y breytist þegar x hækkar um 1. Það er hallatalan a. Finndu svo y þegar x = 0. Það er b.',example:['Punktarnir (0, 2) og (1, 5): y hækkar úr 2 í 5 þegar x hækkar um 1. Hallatalan er 3.','Þegar x = 0 er y = 2. Því er jafnan y = 3x + 2.'],make(){let a=pick([-4,-3,-2,-1,1,2,3,4]),b=rand(-5,6),fmt=(m,n)=>`y = ${m}x ${n<0?'− '+Math.abs(n):'+ '+n}`;return task(`Lína fer í gegnum (0, ${b}) og (1, ${a+b}). Hver er jafna línunnar?`,fmt(a,b),[fmt(b,a),fmt(a,a+b),fmt(-a,b)],`Þegar x hækkar úr 0 í 1 breytist y um ${a}. Því er a = ${a}. Þegar x = 0 er y = ${b}, svo b = ${b}. Jafnan er ${fmt(a,b)}.`,{graph:graph(a,b)})}}
];
function show(html){app.innerHTML=html;app.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})}
function student(){return db.students[person]}
function button(txt,fn,cls='primary'){let b=document.createElement('button');b.textContent=txt;b.className=cls;b.addEventListener('click',fn);return b}
function add(target,...buttons){target.append(...buttons)}
function home(){screen='home';quiz=null;session=null;let names=Object.keys(db.students);show(`<section class="card"><h1>Stærðfræði, skref fyrir skref</h1><p class="lead">Byrjaðu á stuttri könnun eða veldu námsefni. Í hverju stigi færðu útskýringu, sýnidæmi og æfingu.</p><label for="studentName">Nafn nemanda</label><input id="studentName" maxlength="50" autocomplete="name" placeholder="Skrifaðu nafn"><div class="row" id="startActions" style="margin-top:15px"></div><p class="muted small">Könnunin hefur þrjú svör og „Veit ekki“ við hverja spurningu. Hún tekur um 10 mínútur.</p></section>${names.length?`<section class="card"><h2>Halda áfram</h2><div class="row" id="savedNames"></div></section>`:''}<section class="card"><h2>Námsleiðin</h2><div class="grid">${[...new Set(units.map(u=>u.group))].map(g=>`<div class="tile"><h3>${safe(g)}</h3><p>${units.filter(u=>u.group===g).map(u=>safe(u.name)).join(' · ')}</p></div>`).join('')}</div></section>`);add(document.querySelector('#startActions'),button('Hefja nám',()=>{let name=document.querySelector('#studentName').value.trim();if(!name){document.querySelector('#studentName').focus();return}let id=name.toLocaleLowerCase('is');if(!db.students[id])db.students[id]={name,created:new Date().toISOString(),completed:[],attempts:[],placement:null};person=id;save();dashboard()}));let saved=document.querySelector('#savedNames');if(saved)names.forEach(id=>add(saved,button(db.students[id].name,()=>{person=id;dashboard()},'secondary')))}
function dashboard(){screen='dashboard';let s=student();if(!s){home();return}let current=units.findIndex((_,i)=>!s.completed.includes(i));if(current<0)current=units.length-1;let start=s.placement===null?0:s.placement;show(`<section class="card"><h1>Velkomin(n), ${safe(s.name)}</h1><p>${s.placement===null?'Byrjaðu á könnun til að fá tillögu að stigi. Þú mátt líka velja stig sjálf(ur).':`Tillaga úr könnun: <strong>${safe(units[start].name)}</strong>. Þú getur æft hvaða stig sem er.`}</p><div class="row" id="dashActions"></div><p class="small muted">Niðurstöður eru vistaðar sjálfkrafa undir nafninu ${safe(s.name)} í þessum vafra.</p><p class="small muted">Lokið: ${s.completed.length} af ${units.length} stigum.</p><div class="progress" aria-label="${s.completed.length} af ${units.length} stigum lokið"><span style="width:${s.completed.length/units.length*100}%"></span></div></section><section class="grid" id="units">${units.map((u,i)=>`<div class="tile ${i===current?'current':''}"><span class="pill">Stig ${i+1} · ${safe(u.group)}</span><h3>${safe(u.name)}</h3><p class="muted small">${s.completed.includes(i)?'✓ Lokið':i===start?'Tillaga úr könnun':'Útskýring og æfing'}</p><div class="row"><button class="secondary" data-unit="${i}">${s.completed.includes(i)?'Æfa aftur':'Opna stig'}</button><button class="secondary" data-free="${i}">Frjáls æfing</button></div></div>`).join('')}</section>`);add(document.querySelector('#dashActions'),button(s.placement===null?'Taka upphafskönnun':'Taka könnun aftur',diagnostic),button('Áfram í næsta stig',()=>lesson(current),'secondary'));if(s.active&&units[s.active.i])add(document.querySelector('#dashActions'),button(`Halda áfram: ${units[s.active.i].name}`,resume,'secondary'));document.querySelectorAll('[data-unit]').forEach(b=>b.addEventListener('click',()=>lesson(Number(b.dataset.unit))));document.querySelectorAll('[data-free]').forEach(b=>b.addEventListener('click',()=>startFree(Number(b.dataset.free))))}
function diagnostic(){screen='diagnostic';quiz={index:0,answers:[],tasks:units.map(u=>u.make()),chosen:null};quizPage()}
function quizPage(){let q=quiz.tasks[quiz.index],i=quiz.index;show(`<section class="card"><span class="pill">Upphafskönnun</span><h1>Hvar byrjum við?</h1><p>Veldu svar sem þú telur rétt. Ef þú þekkir ekki aðferðina skaltu velja „Veit ekki“.</p><p class="question-number">Spurning ${i+1} af ${units.length} · ${safe(units[i].name)}</p><div class="progress"><span style="width:${i/units.length*100}%"></span></div><div class="math">${safe(q.prompt)}</div><div class="options" id="quizOptions"></div><div id="quizActions" class="row"></div></section>`);let box=document.querySelector('#quizOptions');[...q.options,'Veit ekki'].forEach((v,j)=>add(box,button(v,()=>{quiz.chosen=j===3?null:v;box.querySelectorAll('button').forEach(b=>b.disabled=true);document.querySelector('#quizActions').append(button(i===units.length-1?'Sjá niðurstöðu':'Næsta spurning',()=>{quiz.answers.push(quiz.chosen===q.answer);quiz.index++;quiz.index===units.length?finishDiagnostic():quizPage()}))},'option')))}
function finishDiagnostic(){let s=student();s.placement=quiz.answers.findIndex(x=>!x);if(s.placement<0)s.placement=units.length-1;s.diagnostic={date:new Date().toISOString(),correct:quiz.answers.filter(Boolean).length,total:units.length,answers:quiz.answers};save();let at=s.placement;quiz=null;screen='placement';show(`<section class="card"><h1>Könnun lokið</h1><p>Rétt svör: <strong>${s.diagnostic.correct} af ${units.length}</strong>.</p><p class="lead">Ég legg til að þú byrjir á <strong>stigi ${at+1}: ${safe(units[at].name)}</strong>. Þú getur valið annað stig á námsleiðinni.</p><p class="muted">Tillagan miðast við fyrsta atriðið sem vantaði í könnuninni. Hún er ekki einkunn.</p><div class="row" id="placeActions"></div></section>`);add(document.querySelector('#placeActions'),button('Byrja á stiginu',()=>lesson(at)),button('Skoða öll stig',dashboard,'secondary'))}
function lesson(i){screen='lesson';session={i,mode:'mastery',phase:'explain',tasks:[],index:0,correct:0,hints:0};lessonPage()}
function lessonPage(){let u=units[session.i];show(`<section class="card"><span class="pill">Stig ${session.i+1} af ${units.length} · ${safe(u.group)}</span><h1>${safe(u.name)}</h1><div class="steps"><span class="active">1. Útskýring</span><span>2. Sýnidæmi</span><span>3. Æfing</span></div><p class="lead">${safe(u.intro)}</p><p>Þú færð dæmi sýnt skref fyrir skref á næstu síðu.</p><div class="row" id="lessonActions"></div></section>`);add(document.querySelector('#lessonActions'),button('Sjá sýnidæmi',examplesPage),button('Til baka',dashboard,'secondary'))}
function examplesPage(){session.phase='examples';let u=units[session.i];show(`<section class="card"><span class="pill">Stig ${session.i+1}</span><h1>${safe(u.name)}</h1><div class="steps"><span>1. Útskýring</span><span class="active">2. Sýnidæmi</span><span>3. Æfing</span></div><div class="example"><h2>Sýnidæmi</h2><ol>${u.example.map(x=>`<li>${safe(x)}</li>`).join('')}</ol></div><p>Skoðaðu skrefin. Í æfingunni koma nýjar tölur en sama aðferð.</p><div class="row" id="exampleActions"></div></section>`);add(document.querySelector('#exampleActions'),button('Prófa sjálf(ur)',startPractice),button('Til baka',lessonPage,'secondary'))}
function startPractice(){session.mode='mastery';session.phase='practice';session.tasks=Array.from({length:10},()=>generated(session.i));session.index=0;session.correct=0;session.hints=0;saveActive();practicePage()}
function startFree(i){session={i,mode:'free',phase:'practice',tasks:[generated(i)],index:0,correct:0,hints:0};screen='practice';saveActive();practicePage()}
function practicePage(){let q=session.tasks[session.index],n=session.index,free=session.mode==='free';if(!q){q=generated(session.i);session.tasks[session.index]=q;saveActive()}show(`<section class="card"><span class="pill">Stig ${session.i+1} · ${free?'Frjáls æfing':'Æfing'}</span><h1>${safe(units[session.i].name)}</h1><p class="question-number">Dæmi ${n+1}${free?'':' af 10'} · Rétt: ${session.correct}</p>${free?'<p>Æfðu eins lengi og þú vilt. Ný dæmi koma áfram þar til þú lýkur æfingunni.</p>':`<div class="progress"><span style="width:${n*10}%"></span></div>`}<div class="math">${safe(q.prompt)}</div>${q.graph||''}<p class="muted small">Veldu svarið. Þú getur fengið vísbendingu ef þú þarft.</p><div class="options" id="practiceOptions"></div><div class="row" id="practiceActions"></div><div id="feedback" aria-live="polite"></div></section>`);let box=document.querySelector('#practiceOptions');q.options.forEach(v=>add(box,button(v,()=>answerPractice(v),'option')));add(document.querySelector('#practiceActions'),button('Vísbending',()=>{session.hints++;saveActive();document.querySelector('#feedback').innerHTML=`<div class="feedback try">${safe(units[session.i].intro)}<br>${safe(units[session.i].example[0])}</div>`},'secondary'));if(free)add(document.querySelector('#practiceActions'),button('Ljúka æfingu',finishFree,'secondary'))}
function answerPractice(v){let q=session.tasks[session.index],ok=v===q.answer;if(ok)session.correct++;let box=document.querySelector('#practiceOptions');box.querySelectorAll('button').forEach(b=>{b.disabled=true;if(b.textContent===q.answer)b.classList.add('correct');else if(b.textContent===v)b.classList.add('wrong')});document.querySelector('#practiceActions').innerHTML='';document.querySelector('#feedback').innerHTML=`<div class="feedback ${ok?'good':'try'}"><strong>${ok?'Rétt!':'Skoðum þetta saman.'}</strong><br>${safe(q.why)}</div>`;session.index++;if(session.mode==='free')session.tasks=[generated(session.i)],session.index=0,session.answered=(session.answered||0)+1;saveActive();add(document.querySelector('#practiceActions'),button(session.mode==='mastery'&&session.index===10?'Sjá niðurstöðu':'Næsta dæmi',()=>{if(session.mode==='mastery'&&session.index===10)finishPractice();else practicePage()}));if(session.mode==='free')add(document.querySelector('#practiceActions'),button('Ljúka æfingu',finishFree,'secondary'))}
function finishPractice(){let s=student(),i=session.i,passed=session.correct>=8;s.attempts.push({unit:i,mode:'mastery',date:new Date().toISOString(),correct:session.correct,total:10,hints:session.hints,passed});if(passed&&!s.completed.includes(i))s.completed.push(i);delete s.active;save();screen='result';show(`<section class="card"><h1>${passed?'Stigi lokið!':'Æfum þetta aðeins betur'}</h1><p class="lead">Þú fékkst <strong>${session.correct} af 10</strong> rétt. ${passed?'Þú hefur náð viðmiðinu (8 af 10).':'Til að ljúka stiginu þarf 8 rétt af 10.'}</p><p>${passed?'Þú getur haldið áfram eða æft aftur.':'Farðu aftur yfir útskýringuna og sýnidæmið. Næsta æfing fær önnur dæmi.'}</p><div class="row" id="resultActions"></div></section>`);let target=document.querySelector('#resultActions');if(passed&&i<units.length-1)add(target,button('Næsta stig',()=>lesson(i+1)));add(target,button('Æfa aftur',startPractice,'secondary'),button('Frjáls æfing',()=>startFree(i),'secondary'),button('Útskýring aftur',()=>lesson(i),'secondary'),button('Námsleið',dashboard,'secondary'))}
function finishFree(){let s=student(),total=session.answered||0;if(total)s.attempts.push({unit:session.i,mode:'free',date:new Date().toISOString(),correct:session.correct,total,hints:session.hints,passed:false});delete s.active;save();screen='result';show(`<section class="card"><h1>Æfing lokið</h1><p>Þú leystir ${total} dæmi og fékkst ${session.correct} rétt. Þessi æfing er vistuð undir nafninu ${safe(s.name)}.</p><div class="row" id="resultActions"></div></section>`);add(document.querySelector('#resultActions'),button('Æfa meira',()=>startFree(session.i)),button('Námsleið',dashboard,'secondary'))}
function teacher(){screen='teacher';let records=Object.entries(db.students);show(`<section class="card"><h1>Kennarasvæði</h1><p>Hér sjást aðeins nemendur sem hafa notað þennan vafra á þessu tæki. Niðurstöður berast ekki sjálfkrafa milli tækja.</p><div class="row" id="teacherActions"></div><p class="small muted">Vistaðu afrit reglulega. Ef vafragögnum er eytt eða skipt er um tæki má flytja afrit inn aftur.</p></section><section class="card table-wrap"><table><thead><tr><th>Nemandi</th><th>Könnun</th><th>Tillaga</th><th>Lokið</th><th>Síðasta æfing</th></tr></thead><tbody>${records.length?records.map(([id,s])=>{let last=s.attempts.at(-1);return `<tr><td>${safe(s.name)}</td><td>${s.diagnostic?`${s.diagnostic.correct}/${s.diagnostic.total}`:'—'}</td><td>${s.placement===null?'—':safe(units[s.placement].name)}</td><td>${s.completed.length}/${units.length}</td><td>${last?`${safe(units[last.unit].name)} · ${last.correct}/${last.total}`:'—'}</td></tr>`}).join(''):'<tr><td colspan="5">Engar niðurstöður enn.</td></tr>'}</tbody></table></section>`);add(document.querySelector('#teacherActions'),button('Sækja niðurstöður (CSV)',exportCSV,'secondary'),button('Sækja afrit (JSON)',exportBackup,'secondary'),button('Flytja inn afrit',importBackup,'secondary'),button('Til baka',()=>person?dashboard():home(),'secondary'))}
function exportBackup(){let url=URL.createObjectURL(new Blob([JSON.stringify({version:1,students:db.students},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='algebru-afrit.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function importBackup(){let input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{let data=JSON.parse(await input.files[0].text());if(data.version!==1||!data.students||typeof data.students!=='object'||Array.isArray(data.students))throw Error();for(let [id,s] of Object.entries(data.students)){if(!s||typeof s.name!=='string'||!Array.isArray(s.completed)||!Array.isArray(s.attempts))throw Error();if(!db.students[id])db.students[id]=s;else{let old=db.students[id];old.completed=[...new Set([...old.completed,...s.completed])].filter(i=>Number.isInteger(i)&&i>=0&&i<units.length);let prior=new Set(old.attempts.map(a=>`${a.date}|${a.unit}|${a.mode||'mastery'}`));for(let a of s.attempts)if(!prior.has(`${a.date}|${a.unit}|${a.mode||'mastery'}`))old.attempts.push(a);if(s.diagnostic&&(!old.diagnostic||s.diagnostic.date>old.diagnostic.date)){old.diagnostic=s.diagnostic;old.placement=s.placement}if(!old.active&&s.active)old.active=s.active}}save();teacher();alert('Afritið var flutt inn.')}catch{alert('Ekki tókst að lesa afritið. Veldu JSON-afrit frá þessu forriti.')}};input.click()}
function exportCSV(){let rows=[['Nemandi','Könnun rétt','Könnun alls','Tillaga','Lokið stig','Stig síðustu æfingar','Rétt í síðustu æfingu','Síðasta dagsetning']];Object.values(db.students).forEach(s=>{let a=s.attempts.at(-1);rows.push([s.name,s.diagnostic?.correct??'',s.diagnostic?.total??'',s.placement===null?'':units[s.placement].name,s.completed.length,a?units[a.unit].name:'',a?.correct??'',a?.date??''])});let csv='\ufeff'+rows.map(row=>row.map(v=>{let str=String(v);if(/^[=+@-]/.test(str))str="'"+str;return '"'+str.replaceAll('"','""')+'"'}).join(';')).join('\r\n');let url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='algebru-nidurstodur.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
document.querySelector('#homeBtn').addEventListener('click',home);document.querySelector('#teacherBtn').addEventListener('click',teacher);document.querySelector('#fullscreenBtn').addEventListener('click',()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen?.()});if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('sw.js').catch(()=>{});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;document.querySelector('#installBtn').hidden=false});window.addEventListener('appinstalled',()=>{installPrompt=null;document.querySelector('#installBtn').hidden=true});document.querySelector('#installBtn').addEventListener('click',async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null}else alert('Í Chrome eða Edge: opnaðu valmynd vafrans og veldu „Setja upp app“ eða „Install app“. Á iPhone/iPad: vistaðu fyrst JSON-afrit af eldri niðurstöðum í kennarasvæðinu. Opnaðu síðan síðuna í Safari, veldu Deila og „Bæta við heimaskjá“. Flyttu afritið inn í uppsetta appið ef niðurstöður birtast þar ekki.')});home();
